### Groupby() and agg()

In [1]:
import pandas as pd

In [8]:
df_cars= pd.read_csv('Car_sales.csv')
df_cars = df_cars.iloc[:,0:9].drop(columns=['Model','__year_resale_value'],axis=1)
df_cars

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase
0,Acura,16.919,Passenger,21.50,1.8,140.0,101.2
1,Acura,39.384,Passenger,28.40,3.2,225.0,108.1
2,Acura,14.114,Passenger,NaN,3.2,225.0,106.9
3,Acura,8.588,Passenger,42.00,3.5,210.0,114.6
4,Audi,20.397,Passenger,23.99,1.8,150.0,102.6
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.40,1.9,160.0,100.5
153,Volvo,15.245,Passenger,27.50,2.4,168.0,104.9
154,Volvo,17.531,Passenger,28.80,2.4,168.0,104.9
155,Volvo,3.493,Passenger,45.50,2.3,236.0,104.9
156,Volvo,18.969,Passenger,36.00,2.9,201.0,109.9

In [11]:
# group by manufactuer and calculate the mean
df_cars.groupby('Manufacturer').agg('min')

,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase
Manufacturer,,,,,,
Acura,8.588,Passenger,21.500,1.8,140.0,101.2
Audi,1.380,Passenger,23.990,1.8,150.0,102.6
BMW,9.231,Passenger,26.990,2.5,170.0,107.3
Buick,27.851,Passenger,21.975,3.1,175.0,109.0
Cadillac,6.536,Car,31.010,3.0,200.0,107.4
Chevrolet,17.947,Passenger,9.235,1.0,55.0,93.1
Chrysler,7.854,Car,16.480,2.0,132.0,103.7
Dodge,0.916,Car,12.640,2.0,120.0,96.2
Ford,35.068,Car,12.050,2.0,107.0,98.4
Honda,12.855,Car,12.885,1.6,106.0,103.2
Hyundai,29.450,Passenger,9.699,1.5,92.0,96.1
Infiniti,23.713,Passenger,29.465,3.0,227.0,108.3
Jaguar,15.467,Passenger,42.800,3.0,240.0,114.5
Jeep,55.557,Car,14.460,2.5,120.0,93.4
Lexus,3.334,Car,31.505,3.0,210.0,103.0
Lincoln,13.798,Car,39.080,4.6,215.0,109.0
Mercedes-B,0.954,Car,31.750,2.3,185.0,94.5
Mercury,14.351,Car,16.240,2.0,125.0,106.4
Mitsubishi,0.110,Car,13.987,1.8,113.0,97.2
Nissan,27.308,Car,13.499,1.8,126.0,99.8
Oldsmobile,1.112,Car,18.145,2.4,150.0,107.0
Plymouth,1.872,Car,12.640,2.0,132.0,105.0
Pontiac,19.911,Car,19.720,2.4,150.0,101.1
Porsche,1.280,Passenger,41.430,2.7,217.0,92.6
Saab,9.191,Passenger,26.100,2.0,170.0,102.6
Saturn,5.223,Passenger,10.685,1.9,100.0,102.4
Subaru,33.028,Car,20.095,2.5,165.0,99.4
Toyota,9.835,Car,11.528,1.8,120.0,94.9
Volkswagen,5.596,Passenger,14.900,1.8,115.0,97.4
Volvo,3.493,Passenger,23.400,1.9,160.0,100.5

In [13]:
# find the minimum and maximum values of each column
df_cars.groupby('Vehicle_type').agg(['min','max'])

             Manufacturer         Sales_in_thousands           \
                      min     max                min      max
Vehicle_type
Car              Cadillac  Toyota              9.126  540.561
Passenger           Acura   Volvo              0.110  247.994

             Price_in_thousands         Engine_size      Horsepower         \
                            min     max         min  max        min    max
Vehicle_type
Car                      11.528  60.105         2.0  5.7      119.0  300.0
Passenger                 9.235  85.500         1.0  8.0       55.0  450.0

             Wheelbase
                   min    max
Vehicle_type
Car               93.4  138.7
Passenger         92.6  121.5

In [16]:
# set a name or aggregated column. find the min engine size and max horsepower
df_cars.groupby('Vehicle_type').agg(min_engine_size=('Engine_size','min'),
                                  max_horse_power=('Horsepower','max'))

              min_engine_size  max_horse_power
Vehicle_type
Car                       2.0            300.0
Passenger                 1.0            450.0

In [18]:
#Calculate the sum of sales in thousand and mean of price in thousand
df_cars.groupby('Manufacturer').agg(sum_in_sale=('Sales_in_thousands','sum'),
                                   mean_price =('Price_in_thousands','mean'))

              sum_in_sale  mean_price
Manufacturer
Acura              79.005   30.633333
Audi               40.557   39.980000
BMW                46.505   33.096667
Buick             242.019   26.781250
Cadillac          112.178   40.254000
Chevrolet         554.365   20.022778
Chrysler          201.721   23.430833
Dodge             910.149   24.213636
Ford             2022.635   21.047273
Honda             592.674   20.277000
Hyundai           137.326   12.165667
Infiniti           23.713   29.465000
Jaguar             15.467   42.800000
Jeep              293.153   20.991667
Lexus             106.843   44.055000
Lincoln            85.634   41.690000
Mercedes-B        117.125   52.916667
Mercury           237.999   20.748333
Mitsubishi        180.895   22.167429
Nissan            399.635   22.360714
Oldsmobile        178.989   25.622833
Plymouth           64.001   22.642500
Pontiac           370.534   22.949167
Porsche            12.128   62.473333
Saab               21.306   29.610000
Saturn            168.850   14.271000
Subaru             80.135   21.395000
Toyota            740.205   21.982889
Volkswagen        209.212   17.698333
Volvo              75.740   30.933333