### Groupby()

In [1]:
import pandas as pd

In [10]:
df_cars = pd.read_csv('Car_sales.csv')
df_cars = df_cars.iloc[:,0:9].drop(columns=['Model','__year_resale_value'],axis=1)
df_cars

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase
0,Acura,16.919,Passenger,21.50,1.8,140.0,101.2
1,Acura,39.384,Passenger,28.40,3.2,225.0,108.1
2,Acura,14.114,Passenger,NaN,3.2,225.0,106.9
3,Acura,8.588,Passenger,42.00,3.5,210.0,114.6
4,Audi,20.397,Passenger,23.99,1.8,150.0,102.6
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.40,1.9,160.0,100.5
153,Volvo,15.245,Passenger,27.50,2.4,168.0,104.9
154,Volvo,17.531,Passenger,28.80,2.4,168.0,104.9
155,Volvo,3.493,Passenger,45.50,2.3,236.0,104.9
156,Volvo,18.969,Passenger,36.00,2.9,201.0,109.9

In [14]:
#Group by vehicle type and calculate their max.
df_cars.groupby('Vehicle_type').max()

,Manufacturer,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Wheelbase
Vehicle_type,,,,,,
Car,Toyota,540.561,60.105,5.7,300.0,138.7
Passenger,Volvo,247.994,85.500,8.0,450.0,121.5

In [15]:
#set different index instead of col name
df_cars.groupby('Vehicle_type',as_index=False).min()

,Vehicle_type,Manufacturer,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Wheelbase
0,Car,Cadillac,9.126,11.528,2.0,119.0,93.4
1,Passenger,Acura,0.110,9.235,1.0,55.0,92.6

In [19]:
#Attributes

#print(df_cars.groupby('Manufacturer').groups)
df_cars.groupby('Manufacturer').groups.keys

In [20]:
# get a specific grpup within the manufacturer col
df_cars.groupby('Manufacturer').get_group('Audi')

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase
4,Audi,20.397,Passenger,23.99,1.8,150.0,102.6
5,Audi,18.780,Passenger,33.95,2.8,200.0,108.7
6,Audi,1.380,Passenger,62.00,4.2,310.0,113.0

In [23]:
#group by Manufacturer and calculate their sum
df_cars.groupby('Manufacturer')['Sales_in_thousands'].sum().head()

Manufacturer
Acura        79.005
Audi         40.557
BMW          46.505
Buick       242.019
Cadillac    112.178
Name: Sales_in_thousands, dtype: float64

In [31]:
#find the null values in columns
df_cars[df_cars['Engine_size'].isnull()]

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase
33,Chrysler,53.48,Car,NaN,NaN,NaN,NaN

In [34]:
#group by engine size and count values without dropping the Nan values
df_cars.groupby('Engine_size',dropna=False).count()

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Horsepower,Wheelbase
Engine_size,,,,,,
1.0,1,1,1,1,1,1
1.5,1,1,1,1,1,1
1.6,1,1,1,1,1,1
1.8,8,8,8,8,8,8
1.9,5,5,5,5,5,5
2.0,17,17,17,17,17,17
2.2,4,4,4,4,4,4
2.3,6,6,6,6,6,6
2.4,11,11,11,11,11,11
2.5,11,11,11,11,11,11
2.7,4,4,4,4,4,4
2.8,3,3,3,3,3,3
2.9,1,1,1,1,1,1
3.0,14,14,14,14,14,14
3.1,4,4,4,4,4,4
3.2,6,6,6,5,6,6
3.3,5,5,5,5,5,5
3.4,7,7,7,7,7,7
3.5,8,8,8,8,8,8
3.8,8,8,8,8,8,8
3.9,2,2,2,2,2,2
4.0,7,7,7,7,7,7
4.2,1,1,1,1,1,1
4.3,2,2,2,2,2,2
4.6,9,9,9,9,9,9
4.7,2,2,2,2,2,2
5.0,2,2,2,2,2,2
5.2,2,2,2,2,2,2
5.4,1,1,1,1,1,1
5.7,2,2,2,2,2,2
8.0,1,1,1,1,1,1
NaN,1,1,1,0,0,0