### Interactive Visualizatio with pandas

In [33]:
import pandas as pd
import plotly.express as px

In [19]:
# reading the csv file
df_population_raw = pd.read_csv('population_total.csv')
# dropping null values
df_population_raw.dropna(inplace=True)
# making a pivot table
df_pivot = df_population_raw.pivot(index='year', columns='country',
                                        values='population')
# selecting some countries
df_pivot = df_pivot[['United States', 'India', 'China', 
                          'Indonesia', 'Brazil']]
# showing pivot table
df_pivot

country  United States         India         China    Indonesia       Brazil
year
1955.0     171685336.0  4.098806e+08  6.122416e+08   77273425.0   62533919.0
1960.0     186720571.0  4.505477e+08  6.604081e+08   87751068.0   72179226.0
1965.0     199733676.0  4.991233e+08  7.242190e+08  100267062.0   83373530.0
1970.0     209513341.0  5.551898e+08  8.276014e+08  114793178.0   95113265.0
1975.0     219081251.0  6.231029e+08  9.262409e+08  130680727.0  107216205.0
1980.0     229476354.0  6.989528e+08  1.000089e+09  147447836.0  120694009.0
1985.0     240499825.0  7.843600e+08  1.075589e+09  164982451.0  135274080.0
1990.0     252120309.0  8.732778e+08  1.176884e+09  181413402.0  149003223.0
1995.0     265163745.0  9.639226e+08  1.240921e+09  196934260.0  162019896.0
2000.0     281710909.0  1.056576e+09  1.290551e+09  211513823.0  174790340.0
2005.0     294993511.0  1.147610e+09  1.330776e+09  226289470.0  186127103.0
2010.0     309011475.0  1.234281e+09  1.368811e+09  241834215.0  195713635.0
2015.0     320878310.0  1.310152e+09  1.406848e+09  258383256.0  204471769.0
2016.0     323015995.0  1.324517e+09  1.414049e+09  261556381.0  206163053.0
2017.0     325084756.0  1.338677e+09  1.421022e+09  264650963.0  207833823.0
2018.0     327096265.0  1.352642e+09  1.427648e+09  267670543.0  209469323.0
2019.0     329064917.0  1.366418e+09  1.433784e+09  270625568.0  211049527.0
2020.0     331002651.0  1.380004e+09  1.439324e+09  273523615.0  212559417.0

In [45]:
# creating line plot with px method
px.line(df_pivot, title='Population over the year in some countries',
        labels={'value':'Population','index':'Years'})

In [48]:
# to comparing two or more countries only 'y' parameter
px.line(df_pivot,title='Comparing the population between India nd China',
        labels={'value':'Population','year':'Years'},
        y=['China','India'])

### Bar plots

In [110]:
#single bar plots
df_bar = df_pivot[df_pivot.index.isin([2016])]
df_bar_main = df_bar.T
df_bar

country  United States         India         China    Indonesia       Brazil
year
2016.0     323015995.0  1.324517e+09  1.414049e+09  261556381.0  206163053.0

In [109]:
px.bar(df_bar,labels={'value':'Population','country':'Country'},barmode='group')


### Barplots grouped by n variables

In [71]:
#creating dataframe with some selected years
df_bar_n = df_pivot[df_pivot.index.isin([2005,2010,2015,2020])]
df_bar_n_t = df_bar_n.T
df_bar_n

country  United States         India         China    Indonesia       Brazil
year
2005.0     294993511.0  1.147610e+09  1.330776e+09  226289470.0  186127103.0
2010.0     309011475.0  1.234281e+09  1.368811e+09  241834215.0  195713635.0
2015.0     320878310.0  1.310152e+09  1.406848e+09  258383256.0  204471769.0
2020.0     331002651.0  1.380004e+09  1.439324e+09  273523615.0  212559417.0

In [88]:
px.bar(df_bar_n,barmode='group',orientation='v')

### Pie chart

In [104]:
df_pie = df_pivot[df_pivot.index.isin([2020])]
df_pie_r =df_pie.rename(index={2020:'2020'})
df_pie_r

country  United States         India         China    Indonesia       Brazil
year
2020       331002651.0  1.380004e+09  1.439324e+09  273523615.0  212559417.0

In [117]:
df_2020 =df_pivot.loc[2020]
df_2020

country
United States    3.310027e+08
India            1.380004e+09
China            1.439324e+09
Indonesia        2.735236e+08
Brazil           2.125594e+08
Name: 2020.0, dtype: float64

In [120]:
px.pie(values=df_2020.values,
names=df_2020.index)

### Box plot

In [130]:
df_box = df_pivot[['India','China','Brazil']]
px.box(df_pivot, x=['India','China'], labels={'variable':'Country','value':'Population'})

### Area plot

In [132]:
px.area(df_pivot,labels={'value':'Population','year':'Years'})

### Histogram

In [133]:
px.histogram(df_pivot)

### Scatter Graph

In [134]:
px.scatter(df_pivot)